FNO:
  NIFTY:
    INDEX: NIFTY50
    OPTION: NIFTY

  BANKNIFTY:
    INDEX: BANKNIFTY
    OPTION: BANKNIFTY

  FINNIFTY:
    INDEX: FINNIFTY
    OPTION: FINNIFTY

  INDIAVIX:
    INDEX: INDIAVIX
    OPTION: INDIAVIX

  SENSEX:
    INDEX: SENSEX
    OPTION: SENSEX